### ISSUE TITLE
Testing Transaction-Refactor

### ISSUE THREAD

**Issue by HenryNguyen5** [MyEtherWallet/MyEtherWallet#482]
Below is a non-exaustive spec of the refactor that should be tested

## Signing 
- [ ] Make sure the right wallet is selected when signing, as in local wallet vs web3 wallet 
- [ ] When a transaction sign fails, the state should stay the same except an error notification should be given

## Validation
- [ ] Any invalid fields should have that field's `value` property set to null 
- [ ] Validate `Data` input
- [ ] Validate `To` input 
- [ ] Validate `Gas limit` input 
- [ ] Validate `Nonce`

### For Ether 
- [ ] Should display to the user the current ether value they've inputted
- [ ] Should validate total ether + gasLimit*gasPrice against their input 
### For tokens
- [ ] should display to the user the current token value they've inputted
- [ ] Should validate total tokens + gasLimit*gasPrice against their input 

### For Ether 
- [ ]  Should display the current `to` value
### For tokens
- [ ] Should display the current `TokenTo` value

## Nonce 
- [ ] Manual entry field should be displayed if any offline state is true
- [ ] If network request fails, it should retry and/or display manual entry 
- [ ] Should be in a saga and tested, and grabbed when it's related component is mounted

## Token / Ether swap 
- [ ] Swapping is done by the `UnitDropdown` component which changes the `meta` `decimal` and `unit` fields to the appropriate values
- [ ] When swapping from one unit to another, the previously invalid `value/tokenValue` field may become valid for the new unit as long as its still a valid number. The `raw` value of the `value/tokenValue` field should be taken and converted into a `value` then validated against the user's balance of the new unit. Either `value` or `tokenValue` fields are selected depending if the current unit is a token or ether.

### Ether -> Token swap
- [ ]  should clear the `data` field then replace it with token encoded data
- [ ] should change the `To` field to the token address, and set the old value of the `To` field to a meta `TokenTo` field (which gets encoded into the data)
- [ ] Same thing as above applies to the `Value` field when swapping from ether to a token
- [ ] `Value` field should be cleared

### Token -> Token swap 
- [ ] should re-encode `data` with the proper decimal, and change the `to` field with the right contract address 

### Token -> Ether Swap
- [ ] should clear the `data` field 
- [ ] should clear the `TokenTo` and `TokenValue` `meta` fields

## Gas estimation
- [ ] When any change in `data` or `to` or `value` is observed, gas estimation should be re-done
- [ ] Gas estimation should be debounced, but the latest value should always be resolved 
- [ ] Failure of a network estimation call should have a offline-fallback and/or re-doing of the network call

### Todo (spec out)
- [ ] Test web3/metamask interactions

**Comment by HenryNguyen5** [comment]
Covered in #456
